version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 